# Generated by Django 4.2.1 on 2023-07-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_seats',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
